In [94]:
import pandas as pd
import numpy as np

In [95]:
#Datesets uk
df_collisions_uk = pd.read_csv('../../data/raw/uk/collisions/dft-road-casualty-statistics-collision-2024.csv',low_memory=False)
df_vehicles_uk = pd.read_csv('../../data/raw/uk/collisions/dft-road-casualty-statistics-vehicle-2024.csv',low_memory=False)
df_casualties_uk = pd.read_csv('../../data/raw/uk/collisions/dft-road-casualty-statistics-casualty-2024.csv',low_memory=False)

### Length of individual datasets

In [96]:
print(len(df_collisions_uk))
print(len(df_vehicles_uk))
print(len(df_casualties_uk))

100927
183514
128272

In [97]:
#make entry to list if one accident appears more than on in df
def to_list_if_needed(x): 
    uniq = pd.unique(x)
    if len(uniq) == 1:
        return uniq[0]
    else:
        return uniq.tolist()

# one entry for every collision
df_vehicles_uk_clean = df_vehicles_uk.groupby('collision_index').agg(to_list_if_needed).reset_index()
df_vehicles_uk_clean

,collision_index,collision_year,collision_ref_no,vehicle_reference,vehicle_type,towing_and_articulation,vehicle_manoeuvre_historic,vehicle_manoeuvre,vehicle_direction_from,vehicle_direction_to,...,age_of_driver,age_band_of_driver,engine_capacity_cc,propulsion_code,age_of_vehicle,generic_make_model,driver_imd_decile,lsoa_of_driver,escooter_flag,driver_distance_banding
0,2024010486807,2024,010486807,"[2, 1]","[9, 1]","[0, 9]",99,99,9,9,...,"[-1, 25]","[-1, 5]","[2494, -1]","[8, -1]","[6, -1]","[LEXUS NX 300, -1]","[8, 6]","[E01000241, E01000142]",0,"[2, 1]"
1,2024010486821,2024,010486821,"[2, 3, 1]",9,"[9, 0]",99,99,9,9,...,"[-1, 50, 20]","[-1, 8, 4]",-1,-1,-1,-1,"[-1, 9, 4]","[-1, E01001417, E01023783]",0,"[-1, 1, 4]"
2,2024010486824,2024,010486824,"[1, 2]",9,0,"[18, 2]","[19, 2]","[7, 0]","[3, 0]",...,"[40, -1]","[7, -1]","[998, 1598]",1,"[6, 13]","[FORD FIESTA, VAUXHALL ASTRA]","[8, -1]","[E01002366, -1]",0,"[1, -1]"
3,2024010486825,2024,010486825,"[1, 2]","[3, 9]",0,"[3, 5]","[3, 5]",1,5,...,"[33, -1]","[6, -1]",-1,-1,-1,-1,"[2, -1]","[E01001687, -1]",0,"[1, -1]"
4,2024010486828,2024,010486828,1,11,0,9,9,7,5,...,59,9,-1,-1,-1,-1,3,E01003193,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100922,2024991578008,2024,991578008,"[1, 2]",9,0,-1,"[13, 9]",5,1,...,"[70, 57]","[10, 9]","[3200, -1]","[2, -1]","[7, -1]","[MITSUBISHI SHOGUN, -1]","[5, -1]",-1,0,"[1, -1]"
100923,2024991578058,2024,991578058,"[1, 2]","[9, 1]",0,-1,"[2, 14]","[0, 1]","[0, 5]",...,"[62, 65]",9,"[998, -1]","[1, -1]","[10, -1]","[FORD FIESTA, -1]","[-1, 6]",-1,0,"[-1, 1]"
100924,2024991579036,2024,991579036,1,19,0,-1,7,3,5,...,49,8,1996,2,1,MAXUS DELIVER,4,-1,0,4
100925,2024991579213,2024,991579213,"[1, 2]",9,0,-1,"[19, 7]","[2, 7]",6,...,"[42, 68]","[7, 10]","[2231, -1]","[2, -1]","[10, -1]","[CHEVROLET CAPTIVA, -1]","[10, 7]",-1,0,"[1, 2]"
100926,2024991580347,2024,991580347,"[1, 2]",9,0,-1,"[19, 15]","[3, 7]","[7, 3]",...,"[78, 34]","[11, 6]","[1968, 1461]",2,"[7, 8]","[AUDI Q2, RENAULT CLIO]","[6, 3]",-1,0,1

In [98]:
# one entry for every collision
df_casualties_uk_clean = df_casualties_uk.groupby('collision_index').agg(to_list_if_needed).reset_index()
df_casualties_uk_clean

,collision_index,collision_year,collision_ref_no,vehicle_reference,casualty_reference,casualty_class,sex_of_casualty,age_of_casualty,age_band_of_casualty,casualty_severity,...,bus_or_coach_passenger,pedestrian_road_maintenance_worker,casualty_type,casualty_imd_decile,lsoa_of_casualty,enhanced_casualty_severity,casualty_injury_based,casualty_adjusted_severity_serious,casualty_adjusted_severity_slight,casualty_distance_banding
0,2024010486807,2024,010486807,1,1,1,-1,25,5,3,...,0,0,1,6,E01000142,3,1,0.0,1.0,1
1,2024010486821,2024,010486821,"[1, 2]","[1, 2]","[1, 2]","[1, -1]","[20, -1]","[4, -1]",3,...,0,0,9,"[4, 3]","[E01023783, E01001440]",3,1,0.0,1.0,"[4, 2]"
2,2024010486824,2024,010486824,1,1,1,2,40,7,3,...,0,0,9,8,E01002366,3,1,0.0,1.0,1
3,2024010486825,2024,010486825,1,1,1,1,33,6,3,...,0,0,3,2,E01001687,3,1,0.0,1.0,1
4,2024010486828,2024,010486828,1,1,3,2,39,7,3,...,0,0,0,3,E01003310,3,1,0.0,1.0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100922,2024991578008,2024,991578008,2,"[1, 2]","[2, 1]","[2, 1]","[55, 57]","[8, 9]",3,...,0,0,9,-1,-1,3,1,0.0,1.0,-1
100923,2024991578058,2024,991578058,2,1,1,1,65,9,3,...,0,0,1,6,-1,3,1,0.0,1.0,1
100924,2024991579036,2024,991579036,1,1,3,1,60,9,3,...,0,-1,0,10,-1,3,1,0.0,1.0,1
100925,2024991579213,2024,991579213,1,1,2,1,16,4,3,...,0,0,9,-1,-1,3,1,0.0,1.0,-1
100926,2024991580347,2024,991580347,2,1,1,2,34,6,3,...,0,0,9,3,-1,3,1,0.0,1.0,1

In [99]:
# pedestrian = df_casualties_uk_clean['casualty_class'] == 3
# print(pedestrian.sum())
# pedestrians = df_casualties_uk['casualty_type'] == 0
# print(pedestrians.sum())
# casu = df_casualties_uk['casualty_class'] == 3
# print(casu.sum())


# unique_ids =df_casualties_uk[df_casualties_uk['casualty_class'] == 3]['collision_index'].unique()
# anzahl = unique_ids.shape[0]
# print(anzahl,'ped')



# ped_df = df_casualties_uk_clean[df_casualties_uk_clean['casualty_type'] == 0]
#print(fahr_df)
#peds = ped_df.groupby('collision_index').size()
#print("number pedestrians with accidents", sum(peds))
# print(sum(peds > 1))
# print(sum(peds) - sum(peds > 1))

In [100]:
#print(df_casualties_uk_clean['casualty_type'].to_list())

In [101]:
common_columns = df_collisions_uk.columns.intersection(df_vehicles_uk.columns).tolist()
print(common_columns)

['collision_index', 'collision_year', 'collision_ref_no']

In [102]:
#merge collisions and vehicles
merged_df_uk = pd.merge(df_collisions_uk, df_vehicles_uk_clean, on=common_columns, how='outer', suffixes=('_1', '_2'))
print(merged_df_uk.shape)
# merged_df_uk = pd.concat((df_collisions_uk, df_vehicles_uk_clean),axis=1)
merged_df_uk

(100927, 73)

,collision_index,collision_year,collision_ref_no,location_easting_osgr,location_northing_osgr,longitude,latitude,police_force,collision_severity,number_of_vehicles,...,age_of_driver,age_band_of_driver,engine_capacity_cc,propulsion_code,age_of_vehicle,generic_make_model,driver_imd_decile,lsoa_of_driver,escooter_flag,driver_distance_banding
0,2024010486807,2024,010486807,527188,184782,-0.16712,51.54761,1,3,2,...,"[-1, 25]","[-1, 5]","[2494, -1]","[8, -1]","[6, -1]","[LEXUS NX 300, -1]","[8, 6]","[E01000241, E01000142]",0,"[2, 1]"
1,2024010486821,2024,010486821,528936,194721,-0.13828,51.63653,1,3,3,...,"[-1, 50, 20]","[-1, 8, 4]",-1,-1,-1,-1,"[-1, 9, 4]","[-1, E01001417, E01023783]",0,"[-1, 1, 4]"
2,2024010486824,2024,010486824,552699,185940,0.20103,51.55169,1,3,2,...,"[40, -1]","[7, -1]","[998, 1598]",1,"[6, 13]","[FORD FIESTA, VAUXHALL ASTRA]","[8, -1]","[E01002366, -1]",0,"[1, -1]"
3,2024010486825,2024,010486825,545623,177185,0.09543,51.47489,1,3,2,...,"[33, -1]","[6, -1]",-1,-1,-1,-1,"[2, -1]","[E01001687, -1]",0,"[1, -1]"
4,2024010486828,2024,010486828,536554,178468,-0.03457,51.48868,1,3,1,...,59,9,-1,-1,-1,-1,3,E01003193,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100922,2024991578008,2024,991578008,190198,627793,-5.32322,55.49874,99,3,2,...,"[70, 57]","[10, 9]","[3200, -1]","[2, -1]","[7, -1]","[MITSUBISHI SHOGUN, -1]","[5, -1]",-1,0,"[1, -1]"
100923,2024991578058,2024,991578058,343704,732367,-2.91560,56.48003,99,3,2,...,"[62, 65]",9,"[998, -1]","[1, -1]","[10, -1]","[FORD FIESTA, -1]","[-1, 6]",-1,0,"[-1, 1]"
100924,2024991579036,2024,991579036,354980,685252,-2.72450,56.05799,99,3,1,...,49,8,1996,2,1,MAXUS DELIVER,4,-1,0,4
100925,2024991579213,2024,991579213,270691,650765,-4.06082,55.73297,99,3,2,...,"[42, 68]","[7, 10]","[2231, -1]","[2, -1]","[10, -1]","[CHEVROLET CAPTIVA, -1]","[10, 7]",-1,0,"[1, 2]"
100926,2024991580347,2024,991580347,326744,692503,-3.17980,56.11963,99,3,2,...,"[78, 34]","[11, 6]","[1968, 1461]",2,"[7, 8]","[AUDI Q2, RENAULT CLIO]","[6, 3]",-1,0,1

In [103]:
#merge all also casualities
merged_df_uk_all = pd.merge(merged_df_uk, df_casualties_uk_clean, on=common_columns, how='outer', suffixes=('_1', '_2'))
print(merged_df_uk_all.shape)
print(df_collisions_uk.shape)
#merged_df_uk_all

(100927, 93)
(100927, 44)

In [104]:
#print(merged_df_uk_all.columns)
print(merged_df_uk_all.shape)
final_merged_df_uk = merged_df_uk_all.drop(['vehicle_reference_2'],axis=1)

(100927, 93)

In [105]:
#store all data uk 
final_merged_df_uk.to_csv('../../data/preprocessed/uk/collisions/intermediate_steps/all_data_2024_uk.csv', index=False)
final_merged_df_uk
#merged_df_uk_all['vehicle_type'].to_list()

,collision_index,collision_year,collision_ref_no,location_easting_osgr,location_northing_osgr,longitude,latitude,police_force,collision_severity,number_of_vehicles,...,bus_or_coach_passenger,pedestrian_road_maintenance_worker,casualty_type,casualty_imd_decile,lsoa_of_casualty,enhanced_casualty_severity,casualty_injury_based,casualty_adjusted_severity_serious,casualty_adjusted_severity_slight,casualty_distance_banding
0,2024010486807,2024,010486807,527188,184782,-0.16712,51.54761,1,3,2,...,0,0,1,6,E01000142,3,1,0.0,1.0,1
1,2024010486821,2024,010486821,528936,194721,-0.13828,51.63653,1,3,3,...,0,0,9,"[4, 3]","[E01023783, E01001440]",3,1,0.0,1.0,"[4, 2]"
2,2024010486824,2024,010486824,552699,185940,0.20103,51.55169,1,3,2,...,0,0,9,8,E01002366,3,1,0.0,1.0,1
3,2024010486825,2024,010486825,545623,177185,0.09543,51.47489,1,3,2,...,0,0,3,2,E01001687,3,1,0.0,1.0,1
4,2024010486828,2024,010486828,536554,178468,-0.03457,51.48868,1,3,1,...,0,0,0,3,E01003310,3,1,0.0,1.0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100922,2024991578008,2024,991578008,190198,627793,-5.32322,55.49874,99,3,2,...,0,0,9,-1,-1,3,1,0.0,1.0,-1
100923,2024991578058,2024,991578058,343704,732367,-2.91560,56.48003,99,3,2,...,0,0,1,6,-1,3,1,0.0,1.0,1
100924,2024991579036,2024,991579036,354980,685252,-2.72450,56.05799,99,3,1,...,0,-1,0,10,-1,3,1,0.0,1.0,1
100925,2024991579213,2024,991579213,270691,650765,-4.06082,55.73297,99,3,2,...,0,0,9,-1,-1,3,1,0.0,1.0,-1
100926,2024991580347,2024,991580347,326744,692503,-3.17980,56.11963,99,3,2,...,0,0,9,3,-1,3,1,0.0,1.0,1

# Now make UK data more similar with Germany with the

## Vehicle types

In [106]:
# reduce vehicle types to german format

mcyle_codes = [2,3,4,5,23,97]

car_codes = [8, 9, 10, 19]

goodsv_codes = [11,20,21,98]

other_codes = [16,17,18,22,90,99]


# casualties
def extract_flags(vehicle_list):
    if not isinstance(vehicle_list, list):
        vehicle_list = [vehicle_list]

    # initialize flags
    flags = {
        "is_car": 0,
        "is_cyle": 0,
        "is_mcyle": 0,
        "is_goodsv": 0,
        "is_other": 0,
    }

    for v in vehicle_list:
        # mapping
        if isinstance(v, list):
            if 1 in v:
                flags["is_cyle"] = 1
        else:
            if v == 1:
                flags["is_cyle"] = 1
            
        if v in mcyle_codes:
            flags["is_mcyle"] = 1

        if v in car_codes:
            flags["is_car"] = 1

        if v in goodsv_codes:
            flags["is_goodsv"] = 1

        if v in other_codes:
            flags["is_other"] = 1
    
    return pd.Series(flags)


# Flags for whole dataset
merged_df_uk_all_flags = merged_df_uk_all['vehicle_type'].apply(extract_flags)


merged_df_uk_all = pd.concat([merged_df_uk_all, merged_df_uk_all_flags], axis=1)

merged_df_uk_all

,collision_index,collision_year,collision_ref_no,location_easting_osgr,location_northing_osgr,longitude,latitude,police_force,collision_severity,number_of_vehicles,...,enhanced_casualty_severity,casualty_injury_based,casualty_adjusted_severity_serious,casualty_adjusted_severity_slight,casualty_distance_banding,is_car,is_cyle,is_mcyle,is_goodsv,is_other
0,2024010486807,2024,010486807,527188,184782,-0.16712,51.54761,1,3,2,...,3,1,0.0,1.0,1,1,1,0,0,0
1,2024010486821,2024,010486821,528936,194721,-0.13828,51.63653,1,3,3,...,3,1,0.0,1.0,"[4, 2]",1,0,0,0,0
2,2024010486824,2024,010486824,552699,185940,0.20103,51.55169,1,3,2,...,3,1,0.0,1.0,1,1,0,0,0,0
3,2024010486825,2024,010486825,545623,177185,0.09543,51.47489,1,3,2,...,3,1,0.0,1.0,1,1,0,1,0,0
4,2024010486828,2024,010486828,536554,178468,-0.03457,51.48868,1,3,1,...,3,1,0.0,1.0,2,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100922,2024991578008,2024,991578008,190198,627793,-5.32322,55.49874,99,3,2,...,3,1,0.0,1.0,-1,1,0,0,0,0
100923,2024991578058,2024,991578058,343704,732367,-2.91560,56.48003,99,3,2,...,3,1,0.0,1.0,1,1,1,0,0,0
100924,2024991579036,2024,991579036,354980,685252,-2.72450,56.05799,99,3,1,...,3,1,0.0,1.0,1,1,0,0,0,0
100925,2024991579213,2024,991579213,270691,650765,-4.06082,55.73297,99,3,2,...,3,1,0.0,1.0,-1,1,0,0,0,0
100926,2024991580347,2024,991580347,326744,692503,-3.17980,56.11963,99,3,2,...,3,1,0.0,1.0,1,1,0,0,0,0

## Pedestrians

In [107]:
def extract_flags(casualty_type_list):
    if not isinstance(casualty_type_list, list):
        casualty_type_list = [casualty_type_list]

    # initialize flags
    flags = {
            "is_pedestrian": 0,
        }
    for v in casualty_type_list:
            # mapping
        if v != 0:
            flags["is_pedestrian"] = 1
        
    return pd.Series(flags)


# Flags for whole dataset

merged_df_uk_all_pedestrian = merged_df_uk_all['pedestrian_location'].apply(extract_flags)

merged_df_uk_all = pd.concat([merged_df_uk_all, merged_df_uk_all_pedestrian], axis=1)

merged_df_uk_all

,collision_index,collision_year,collision_ref_no,location_easting_osgr,location_northing_osgr,longitude,latitude,police_force,collision_severity,number_of_vehicles,...,casualty_injury_based,casualty_adjusted_severity_serious,casualty_adjusted_severity_slight,casualty_distance_banding,is_car,is_cyle,is_mcyle,is_goodsv,is_other,is_pedestrian
0,2024010486807,2024,010486807,527188,184782,-0.16712,51.54761,1,3,2,...,1,0.0,1.0,1,1,1,0,0,0,0
1,2024010486821,2024,010486821,528936,194721,-0.13828,51.63653,1,3,3,...,1,0.0,1.0,"[4, 2]",1,0,0,0,0,0
2,2024010486824,2024,010486824,552699,185940,0.20103,51.55169,1,3,2,...,1,0.0,1.0,1,1,0,0,0,0,0
3,2024010486825,2024,010486825,545623,177185,0.09543,51.47489,1,3,2,...,1,0.0,1.0,1,1,0,1,0,0,0
4,2024010486828,2024,010486828,536554,178468,-0.03457,51.48868,1,3,1,...,1,0.0,1.0,2,0,0,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100922,2024991578008,2024,991578008,190198,627793,-5.32322,55.49874,99,3,2,...,1,0.0,1.0,-1,1,0,0,0,0,0
100923,2024991578058,2024,991578058,343704,732367,-2.91560,56.48003,99,3,2,...,1,0.0,1.0,1,1,1,0,0,0,0
100924,2024991579036,2024,991579036,354980,685252,-2.72450,56.05799,99,3,1,...,1,0.0,1.0,1,1,0,0,0,0,1
100925,2024991579213,2024,991579213,270691,650765,-4.06082,55.73297,99,3,2,...,1,0.0,1.0,-1,1,0,0,0,0,0
100926,2024991580347,2024,991580347,326744,692503,-3.17980,56.11963,99,3,2,...,1,0.0,1.0,1,1,0,0,0,0,0

In [108]:
not_ped = df_casualties_uk['pedestrian_location']!= 0
print('all  pedestrians at collisions' ,not_ped.sum())
unique = df_casualties_uk[df_casualties_uk['pedestrian_location'] != 0]['collision_index'].unique()
print('all collisions with pedestrians',unique.shape[0])
pedestrian = merged_df_uk_all['pedestrian_location'] != 0
print('ped ',pedestrian.sum())


# collisions with pedestrians
# ped = merged_df_uk_all['is_pedestrian'] 
# ped.sum()

all  pedestrians at collisions 19184
all collisions with pedestrians 18467
ped  18467

In [109]:
merged_df_uk_all['is_car']

0         1
1         1
2         1
3         1
4         0
         ..
100922    1
100923    1
100924    1
100925    1
100926    1
Name: is_car, Length: 100927, dtype: int64

In [110]:
# print(merged_df_uk_all['is_car'].sum())
# print(merged_df_uk_all['is_pedestrian'].sum())
# print(merged_df_uk_all['is_other'].sum())
# print(merged_df_uk_all['is_goodsv'].sum())
# print(merged_df_uk_all['is_cyle'].sum())

#test in values are correct for cycles
result_v = merged_df_uk_all['is_cyle'].sum() 
print(result_v)
result_ = df_vehicles_uk['vehicle_type'] == 1
print("all cycle involved in collisions",result_.sum())
cyle_df = df_vehicles_uk[df_vehicles_uk['vehicle_type'] == 1]

cyle = cyle_df.groupby('collision_index').size()
print("number collisions with cycle",cyle.shape[0])
#print(cyler.to_list())
print(cyle.sum())
a_cylerad = cyle[cyle >= 1]
coll_cyle = a_cylerad.count()
coll_cyle

15042
all cycle involved in collisions 15362
number collisions with cycle 15042
15362

np.int64(15042)

In [111]:
# convert dates
merged_df_uk_all['date'] = pd.to_datetime(merged_df_uk_all['date'], format='%d/%m/%Y')

print(merged_df_uk_all['date'])
# year, month, day
merged_df_uk_all['year'] =  merged_df_uk_all['date'].dt.year
merged_df_uk_all['month'] = merged_df_uk_all['date'].dt.month
merged_df_uk_all['day'] =   merged_df_uk_all['date'].dt.day

#print(merged_df_uk_all.columns)
#print(merged_df_uk_all.shape)

merged_df_uk_all = merged_df_uk_all.drop('date', axis=1)

0        2024-01-01
1        2024-01-01
2        2024-01-01
3        2024-01-01
4        2024-01-01
            ...
100922   2024-08-15
100923   2024-11-15
100924   2024-11-07
100925   2024-11-15
100926   2024-11-19
Name: date, Length: 100927, dtype: datetime64[ns]

In [112]:
merged_df_uk_all['light_conditions']

0         4
1         4
2         4
3         4
4         4
         ..
100922    1
100923    1
100924    1
100925    4
100926    1
Name: light_conditions, Length: 100927, dtype: int64

In [113]:
# match light_conditions to german format

merged_df_uk_all.loc[merged_df_uk_all['light_conditions'] == 1, 'light_conditions'] = 0
merged_df_uk_all.loc[merged_df_uk_all['light_conditions'].isin([4, 5, 6, 7]), 'light_conditions'] = 2
merged_df_uk_all.loc[merged_df_uk_all['light_conditions'].isin([-1]), 'light_conditions'] = -1



#merged_df_uk_all['light_conditions'].to_list()

In [114]:
#Road conditions to german format
merged_df_uk_all['road_surface_conditions']

merged_df_uk_all.loc[merged_df_uk_all['road_surface_conditions'] == 1, 'road_surface_conditions'] = 0
merged_df_uk_all.loc[merged_df_uk_all['road_surface_conditions'].isin([2, 5, 6, 7]), 'road_surface_conditions'] = 1
merged_df_uk_all.loc[merged_df_uk_all['road_surface_conditions'].isin([3,4]), 'road_surface_conditions'] = 2
merged_df_uk_all.loc[merged_df_uk_all['road_surface_conditions'].isin([9,-1]), 'road_surface_conditions'] = -1



#merged_df_uk_all['road_surface_conditions']

In [115]:
# Tests
# result = merged_df_uk_all[merged_df_uk_all['casualty_type'] == -1]
# print(len(result))
# result_v = merged_df_uk_all[merged_df_uk_all['casualty_type'] == 0]
# print(len(result_v))
# result_2 = merged_df_uk_all[merged_df_uk_all['casualty_class'] == 3]
# print(len(result_2))

# result_3 = merged_df_uk_all[merged_df_uk_all['pedestrian_location'] == 0]
# print(len(result_3))
# result_4 = merged_df_uk_all[merged_df_uk_all['pedestrian_location'] == -1]
# print(len(result_4))
# print(len(result_3)+len(result_2))
# results = merged_df_uk_all['is_pedestrian'] == 1
# print(results.sum())
# merged_df_uk_all.columns.to_list()

In [116]:
print(merged_df_uk_all.shape)
list_all_columns=merged_df_uk_all.columns.tolist()
print(len(list_all_columns))
list_all_columns

merged_df_uk_all.to_csv('../../data/preprocessed/uk/collisions/intermediate_steps/merged_uk.csv', index=False)

(100927, 101)
101