In [40]:
import pandas as pd

In [41]:
# combined UK dataset
df_collisions_uk = pd.read_csv('../../data/preprocessed/uk/collisions/intermediate_steps/merged_uk.csv',low_memory=False)

In [42]:
print(len(df_collisions_uk.columns.to_list()))

101

In [43]:
df_collisions_uk.columns.to_list()

['collision_index',
 'collision_year',
 'collision_ref_no',
 'location_easting_osgr',
 'location_northing_osgr',
 'longitude',
 'latitude',
 'police_force',
 'collision_severity',
 'number_of_vehicles',
 'number_of_casualties',
 'day_of_week',
 'time',
 'local_authority_district',
 'local_authority_ons_district',
 'local_authority_highway',
 'local_authority_highway_current',
 'first_road_class',
 'first_road_number',
 'road_type',
 'speed_limit',
 'junction_detail_historic',
 'junction_detail',
 'junction_control',
 'second_road_class',
 'second_road_number',
 'pedestrian_crossing_human_control_historic',
 'pedestrian_crossing_physical_facilities_historic',
 'pedestrian_crossing',
 'light_conditions',
 'weather_conditions',
 'road_surface_conditions',
 'special_conditions_at_site',
 'carriageway_hazards_historic',
 'carriageway_hazards',
 'urban_or_rural_area',
 'did_police_officer_attend_scene_of_accident',
 'trunk_road_flag',
 'lsoa_of_accident_location',
 'enhanced_severity_collision',
 'collision_injury_based',
 'collision_adjusted_severity_serious',
 'collision_adjusted_severity_slight',
 'vehicle_reference_1',
 'vehicle_type',
 'towing_and_articulation',
 'vehicle_manoeuvre_historic',
 'vehicle_manoeuvre',
 'vehicle_direction_from',
 'vehicle_direction_to',
 'vehicle_location_restricted_lane_historic',
 'vehicle_location_restricted_lane',
 'junction_location',
 'skidding_and_overturning',
 'hit_object_in_carriageway',
 'vehicle_leaving_carriageway',
 'hit_object_off_carriageway',
 'first_point_of_impact',
 'vehicle_left_hand_drive',
 'journey_purpose_of_driver_historic',
 'journey_purpose_of_driver',
 'sex_of_driver',
 'age_of_driver',
 'age_band_of_driver',
 'engine_capacity_cc',
 'propulsion_code',
 'age_of_vehicle',
 'generic_make_model',
 'driver_imd_decile',
 'lsoa_of_driver',
 'escooter_flag',
 'driver_distance_banding',
 'vehicle_reference_2',
 'casualty_reference',
 'casualty_class',
 'sex_of_casualty',
 'age_of_casualty',
 'age_band_of_casualty',
 'casualty_severity',
 'pedestrian_location',
 'pedestrian_movement',
 'car_passenger',
 'bus_or_coach_passenger',
 'pedestrian_road_maintenance_worker',
 'casualty_type',
 'casualty_imd_decile',
 'lsoa_of_casualty',
 'enhanced_casualty_severity',
 'casualty_injury_based',
 'casualty_adjusted_severity_serious',
 'casualty_adjusted_severity_slight',
 'casualty_distance_banding',
 'is_car',
 'is_cyle',
 'is_mcyle',
 'is_goodsv',
 'is_other',
 'is_pedestrian',
 'year',
 'month',
 'day']

In [44]:
selected_columns = ['collision_index','collision_year',
 'collision_ref_no',
 'location_easting_osgr',
 'location_northing_osgr',
 'longitude',
 'latitude',
 #'police_force',
 'casualty_severity',
 #'number_of_vehicles',
 #'number_of_casualties',
 'day_of_week',
 'time',
 'local_authority_district',
 'local_authority_ons_district',
 #'local_authority_highway',
 #'local_authority_highway_current',
 'first_road_class',
 #'first_road_number',
 #'road_type',
 #'speed_limit',
 #'junction_detail_historic',
 #'junction_detail',
 #'junction_control',
 #'second_road_class',
 #'second_road_number',
 #'pedestrian_crossing_human_control_historic',
 #'pedestrian_crossing_physical_facilities_historic',
 #'pedestrian_crossing',
 'light_conditions',
 'weather_conditions',
 'road_surface_conditions',
 #'special_conditions_at_site',
 #'carriageway_hazards_historic',
 #'carriageway_hazards',
 'urban_or_rural_area',
 #'did_police_officer_attend_scene_of_accident',
 #'trunk_road_flag',
 #'lsoa_of_accident_location',
 #'enhanced_severity_collision',
 #'collision_injury_based',
 #'collision_adjusted_severity_serious',
 #'collision_adjusted_severity_slight',
 #'vehicle_reference_1',
 #'vehicle_type',
 #'towing_and_articulation',
 #'vehicle_manoeuvre_historic',
 'vehicle_manoeuvre',
 'vehicle_direction_from',
 'vehicle_direction_to',
 #'vehicle_location_restricted_lane_historic',
 #'vehicle_location_restricted_lane',
 #'junction_location',
 #'skidding_and_overturning',
 'hit_object_in_carriageway',
 'vehicle_leaving_carriageway',
 'hit_object_off_carriageway',
 #'first_point_of_impact',
 #'vehicle_left_hand_drive',
 #'journey_purpose_of_driver_historic',
 #'journey_purpose_of_driver',
 #'sex_of_driver',
 #'age_of_driver',
 #'age_band_of_driver',
 #'engine_capacity_cc',
 #'propulsion_code',
 #'age_of_vehicle',
 #'generic_make_model',
#  'driver_imd_decile',
#  'lsoa_of_driver',
#  'escooter_flag',
#  'driver_distance_banding',
#  'vehicle_reference_2',
#  'casualty_reference',
#  'casualty_class',
#  'sex_of_casualty',
#  'age_of_casualty',
#  'age_band_of_casualty',
# 'casualty_severity',
#  'pedestrian_location',
#  'pedestrian_movement',
#  'car_passenger',
#  'bus_or_coach_passenger',
#  'pedestrian_road_maintenance_worker',
#  'casualty_type',
#  'casualty_imd_decile',
#  'lsoa_of_casualty',
#  'enhanced_casualty_severity',
#  'casualty_injury_based',
#  'casualty_adjusted_severity_serious',
#  'casualty_adjusted_severity_slight',
#  'casualty_distance_banding',
 'is_car',
 'is_cyle',
 'is_mcyle',
 'is_goodsv',
 'is_other',
 'is_pedestrian',
 #'year',
 'month',
 'day']

## Store final preprocessed version

In [45]:
df_collisions_uk.columns = ['casualty_severity' if col == 'collision_severity' else col for col in df_collisions_uk.columns]

df_reduced_uk = df_collisions_uk[selected_columns]

df_reduced_uk.to_csv('../../data/preprocessed/uk/collisions/preprocessed_uk.csv', index=False)

df_reduced_uk

,collision_index,collision_year,collision_ref_no,location_easting_osgr,location_northing_osgr,longitude,latitude,casualty_severity,casualty_severity,day_of_week,...,vehicle_leaving_carriageway,hit_object_off_carriageway,is_car,is_cyle,is_mcyle,is_goodsv,is_other,is_pedestrian,month,day
0,2024010486807,2024,010486807,527188,184782,-0.16712,51.54761,3,3,2,...,9,99,1,1,0,0,0,0,1,1
1,2024010486821,2024,010486821,528936,194721,-0.13828,51.63653,3,3,2,...,9,99,1,0,0,0,0,0,1,1
2,2024010486824,2024,010486824,552699,185940,0.20103,51.55169,3,3,2,...,0,0,1,0,0,0,0,0,1,1
3,2024010486825,2024,010486825,545623,177185,0.09543,51.47489,3,3,2,...,0,0,1,0,1,0,0,0,1,1
4,2024010486828,2024,010486828,536554,178468,-0.03457,51.48868,3,3,2,...,0,0,0,0,0,1,0,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100922,2024991578008,2024,991578008,190198,627793,-5.32322,55.49874,3,3,5,...,0,0,1,0,0,0,0,0,8,15
100923,2024991578058,2024,991578058,343704,732367,-2.91560,56.48003,3,3,6,...,0,0,1,1,0,0,0,0,11,15
100924,2024991579036,2024,991579036,354980,685252,-2.72450,56.05799,3,3,5,...,0,0,1,0,0,0,0,1,11,7
100925,2024991579213,2024,991579213,270691,650765,-4.06082,55.73297,3,3,6,...,"[0, 1]",0,1,0,0,0,0,0,11,15
100926,2024991580347,2024,991580347,326744,692503,-3.17980,56.11963,3,3,3,...,0,0,1,0,0,0,0,0,11,19

# Adapt german dataset

In [46]:
# collisions germany
df_collisions_ger = pd.read_csv('../../data/raw/germany/collisions/Unfallorte2024_LinRef.csv',delimiter=';',low_memory=False)

In [47]:
print(df_collisions_ger.shape)
print(df_collisions_ger.columns)
#df_collisions_ger

(268519, 26)
Index(['OID_', 'UIDENTSTLAE', 'ULAND', 'UREGBEZ', 'UKREIS', 'UGEMEINDE',
       'UJAHR', 'UMONAT', 'USTUNDE', 'UWOCHENTAG', 'UKATEGORIE', 'UART',
       'UTYP1', 'ULICHTVERH', 'IstStrassenzustand', 'IstRad', 'IstPKW',
       'IstFuss', 'IstKrad', 'IstGkfz', 'IstSonstige', 'LINREFX', 'LINREFY',
       'XGCSWGS84', 'YGCSWGS84', 'PLST'],
      dtype='object')

In [48]:
# new columns german dataset
df_collisions_ger.columns = ['OID_', 'c_id', 'c_Federal_State', 'c_Administrative_region', 'c_Administrative_district', 'c_Municipality',
       'year', 'month', 'hour', 'day_of_week', 'casualty_severity', 'kind_of_accident',
       'type_of_accident', 'light_conditions', 'road_surface_conditions', 'is_cyle', 'is_car',
       'is_pedestrian', 'is_mcyle', 'is_goodsv', 'is_other', 'loc_easting-X', 'loc_northing-Y',
       'longitude', 'latitude', 'PLST']

df_collisions_ger.to_csv('../../data/preprocessed/germany/collisions/intermediate_steps/modified_ger.csv', index=False)
df_collisions_ger

,OID_,c_id,c_Federal_State,c_Administrative_region,c_Administrative_district,c_Municipality,year,month,hour,day_of_week,...,is_car,is_pedestrian,is_mcyle,is_goodsv,is_other,loc_easting-X,loc_northing-Y,longitude,latitude,PLST
0,1,01240526125013102024,1,0,59,44,2024,5,23,1,...,1,0,0,0,0,"525162,376299999654293","6045497,205000000074506","9,389075627000068","54,556379612000057",1
1,2,01240526105132502024,1,0,62,94,2024,5,23,1,...,1,0,0,0,0,"600576,090200000442564","5964744,324200000613928","10,527878375000057","53,821498344000076",1
2,3,01240525171013972024,1,0,60,88,2024,5,18,7,...,0,0,1,0,0,"574734,079499999992549","5969976,972100000828505","10,136678418000031","53,872878104000051",1
3,4,01240525171013602024,1,0,60,47,2024,5,16,7,...,1,0,0,0,0,"567578,579099999740720","5963041,894099999219179","10,026340679000043","53,811535772000070",1
4,5,01240525171013522024,1,0,60,4,2024,5,19,7,...,1,0,0,0,0,"561431,042000000365078","5973289,735400000587106","9,935041162000061","53,904394936000074",1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
268514,268515,10240927009432524520,10,0,42,116,2024,9,17,6,...,0,0,0,0,0,"351516,032639690383803","5494758,855163721367717","6,945610149000061","49,587166386000035",2
268515,268516,10240927009522524460,10,0,45,114,2024,9,15,6,...,0,0,0,0,0,"379086,205409424670506","5464820,163632288575172","7,336015290000034","49,324126323000030",2
268516,268517,10241001009422500650,10,0,42,114,2024,10,14,3,...,0,0,0,0,0,"320899,135468380758539","5486168,528676146641374","6,526285881000035","49,501680514000043",2
268517,268518,10241011009422509150,10,0,42,115,2024,10,13,6,...,1,0,0,0,0,"318284,435264870757237","5481027,171240657567978","6,492569665000076","49,454701525000075",2
268518,268519,10241109009422506630,10,0,42,114,2024,11,15,7,...,0,0,0,0,0,"321855,003343698917888","5483322,633817158639431","6,540757584000062","49,476387168000031",2

## Add urban_or_rural_area column to the german dataset

In [49]:
# collisions urban area germany
df_urban_rural_ger = pd.read_csv('../../data/preprocessed/germany/collisions/intermediate_steps/collisions_urban_area_ger.csv',low_memory=False, dtype={'c_id': str})
# german collision dataset 
#df_collisions_ger = pd.read_csv('../data/processed/modified_ger.csv',low_memory=False, dtype={'c_id': str})
print(df_urban_rural_ger['c_id'].dtypes)
print(df_collisions_ger['c_id'].dtypes)

object
object

In [50]:

df_collisions_ger['urban_or_rural_area'] = df_collisions_ger['c_id'].isin(df_urban_rural_ger['c_id']).map({True: 1, False: 2})
df_collisions_ger

,OID_,c_id,c_Federal_State,c_Administrative_region,c_Administrative_district,c_Municipality,year,month,hour,day_of_week,...,is_pedestrian,is_mcyle,is_goodsv,is_other,loc_easting-X,loc_northing-Y,longitude,latitude,PLST,urban_or_rural_area
0,1,01240526125013102024,1,0,59,44,2024,5,23,1,...,0,0,0,0,"525162,376299999654293","6045497,205000000074506","9,389075627000068","54,556379612000057",1,2
1,2,01240526105132502024,1,0,62,94,2024,5,23,1,...,0,0,0,0,"600576,090200000442564","5964744,324200000613928","10,527878375000057","53,821498344000076",1,2
2,3,01240525171013972024,1,0,60,88,2024,5,18,7,...,0,1,0,0,"574734,079499999992549","5969976,972100000828505","10,136678418000031","53,872878104000051",1,2
3,4,01240525171013602024,1,0,60,47,2024,5,16,7,...,0,0,0,0,"567578,579099999740720","5963041,894099999219179","10,026340679000043","53,811535772000070",1,2
4,5,01240525171013522024,1,0,60,4,2024,5,19,7,...,0,0,0,0,"561431,042000000365078","5973289,735400000587106","9,935041162000061","53,904394936000074",1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
268514,268515,10240927009432524520,10,0,42,116,2024,9,17,6,...,0,0,0,0,"351516,032639690383803","5494758,855163721367717","6,945610149000061","49,587166386000035",2,1
268515,268516,10240927009522524460,10,0,45,114,2024,9,15,6,...,0,0,0,0,"379086,205409424670506","5464820,163632288575172","7,336015290000034","49,324126323000030",2,1
268516,268517,10241001009422500650,10,0,42,114,2024,10,14,3,...,0,0,0,0,"320899,135468380758539","5486168,528676146641374","6,526285881000035","49,501680514000043",2,1
268517,268518,10241011009422509150,10,0,42,115,2024,10,13,6,...,0,0,0,0,"318284,435264870757237","5481027,171240657567978","6,492569665000076","49,454701525000075",2,1
268518,268519,10241109009422506630,10,0,42,114,2024,11,15,7,...,0,0,0,0,"321855,003343698917888","5483322,633817158639431","6,540757584000062","49,476387168000031",2,1

## Store final preprocessed version

In [51]:
df_collisions_ger.to_csv('../../data/preprocessed/germany/collisions/preprocessed_ger.csv', index=True)

In [52]:
couter =df_collisions_ger['urban_or_rural_area'].value_counts()
couter

urban_or_rural_area
1    206756
2     61763
Name: count, dtype: int64